---
ID: "93d14404-da18-4974-8a95-e15bddd3fa39"
Parent: "c3bf1dde-8a85-4599-bb0e-d8ba8e980e19"
Template: "c3bf1dde-8a85-4599-bb0e-d8ba8e980e19"
Path: "/sitecore/templates/Project/Mahen-XM-Cloud-Test/Partial Design Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C3BF1DDE-8A85-4599-BB0E-D8BA8E980E19}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240611T122953Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mahendra_kumar_meena@epam.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mahendra_kumar_meena@epam.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "79bedd06-b187-4c33-9fc1-b05b44c0e966"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mahendra_kumar_meena@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240611T122956Z
