---
ID: "5c2445e9-51a7-41f7-a68d-83480af34938"
Parent: "249a9c7d-bad8-451f-8d95-cc1a393b40f5"
Template: "249a9c7d-bad8-451f-8d95-cc1a393b40f5"
Path: /sitecore/templates/System/Layout/Preview Simulators/Trait/__Standard Values
SharedFields:
- ID: "fe5c1799-fa2a-4a5a-9c2b-d67bc1668d28"
  Hint: Type
  Value: Sitecore.Pipelines.ProcessSimulatorResponse.ProcessHtml, Sitecore.Kernel
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20110720T153400
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "73fb536c-7c98-461b-a93c-fae772011889"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20120321T161535:634679433350861246"
