---
ID: "9cfbc692-38f3-447a-b847-b98450655c57"
Parent: "adb6ca4f-03ef-4f47-b9ac-9ce2ba53ff97"
Template: "adb6ca4f-03ef-4f47-b9ac-9ce2ba53ff97"
Path: /sitecore/templates/System/Item Buckets/Bucket/__Standard Values
SharedFields:
- ID: "39c4902e-9960-4469-aeef-e878e9c8218f"
  Hint: __Hidden
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111026T152100
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6ebfe4a0-33df-4b99-adb5-63addfa90911"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20120511T144511:634723443117594019"
