---
ID: "f6ffa843-93e3-4801-8abc-ce39300fa70c"
Parent: "d5846f4f-f6d9-4add-8e8d-01a53f2b5ddf"
Template: "d5846f4f-f6d9-4add-8e8d-01a53f2b5ddf"
Path: /sitecore/templates/Feature/Experience Accelerator/Page Content/Rendering Parameters/Title/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150929T064843Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9fb636fe-bfc5-46d3-8c3f-3c7fd50e2f77"
