---
ID: "5a326657-340f-4f08-95cd-9bb314cbe561"
Parent: "9f6e14e6-c593-410b-a57e-21f6b5a413ad"
Template: "9f6e14e6-c593-410b-a57e-21f6b5a413ad"
Path: /sitecore/templates/System/Item Buckets/Item Buckets Settings/__Standard Values
SharedFields:
- ID: "5a81d794-7364-4cc5-8aa9-a921d5dda4af"
  Hint: Opening Search Results
  Value: New Tab
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111103T104700
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5769ddf1-b378-4b4d-b5ce-2eddca0f9667"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130206T122205:634957501254596355"
