---
ID: "162df5a5-66ec-4e50-b211-7dc4322ab884"
Parent: "a7837de9-3266-46cb-a945-62c55da45e9e"
Template: "a7837de9-3266-46cb-a945-62c55da45e9e"
Path: /sitecore/templates/Foundation/Experience Accelerator/Local Datasources/Global Datasource Behavior/__Standard Values
SharedFields:
- ID: "c80e6f3c-5bcd-426b-b1eb-6d10672e985d"
  Hint: Data Source Selection Behavior
  Value: DoNotCopy
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171127T141557Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8c618507-9148-45f8-9bea-0a81cd983ef2"
