---
ID: "9c1c7f87-94cb-4811-b2b0-619035b0be15"
Parent: "af1cc1af-99cc-4e3c-9a26-3ead62890fce"
Template: "af1cc1af-99cc-4e3c-9a26-3ead62890fce"
Path: /sitecore/templates/Feature/Experience Accelerator/Events/Datasource/Events Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {311E5F53-CF27-4A85-B887-B84BEE5D3BA3}
    {AF1CC1AF-99CC-4E3C-9A26-3EAD62890FCE}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130326T113400Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "64150883-7e05-4cf1-82be-857fe924e39b"
