---
ID: "2c228411-8fcd-4128-90a2-5c56cc842ffb"
Parent: "f9a7c944-ad85-4d0a-86e8-1d1b3af814b8"
Template: "f9a7c944-ad85-4d0a-86e8-1d1b3af814b8"
Path: /sitecore/templates/Foundation/Experience Accelerator/Json Variants/JSON Placeholder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170307T123113Z
    - ID: "318cdb5d-2435-4961-8ef7-b18a38023237"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "45cc5e35-7fa4-4e93-b7a8-6f8d62cbdcb5"
