---
ID: "706d28b9-c079-4cb4-bc66-1fefc9bca01b"
Parent: "4bbfe581-9c3c-436a-9c27-e981c415ed5a"
Template: "4bbfe581-9c3c-436a-9c27-e981c415ed5a"
Path: /sitecore/templates/Foundation/Experience Accelerator/FEaaS/Rendering Parameters/BYOC Wrapper Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230726T114123Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "22bce48f-baad-4a7a-9c82-3bda409bd038"
