---
ID: "41a483f7-9b2e-4790-80d4-1bc860f523e0"
Parent: "e642ef3a-acf4-4238-b847-ce504c1e9780"
Template: "e642ef3a-acf4-4238-b847-ce504c1e9780"
Path: /sitecore/templates/System/Services/OData Item API Key/__Standard Values
SharedFields:
- ID: "3f6ae238-af94-4e0a-a5d6-0e0c3ba683a3"
  Hint: Search Filter
  Value: IsLatestVersion eq true
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170411T072557Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7404cca9-1dbd-41f5-9f37-a0b15144cfdf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170523T150946Z
