---
ID: "8fadfe82-58ed-45a5-8ec5-69bcae8fc3d5"
Parent: "9c0dac28-08aa-4b44-bc21-53363206f6a5"
Template: "9c0dac28-08aa-4b44-bc21-53363206f6a5"
Path: /sitecore/templates/Foundation/Experience Accelerator/Theming/Folders/Styles/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160621T115020Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c12a64ad-3d13-40f1-84d2-aa7372b15ef6"
