---
ID: "44a63ebd-641e-44b4-a30c-616a7202cbe4"
Parent: "a825775a-f3bb-4c91-9341-5a0d1314131d"
Template: "a825775a-f3bb-4c91-9341-5a0d1314131d"
Path: /sitecore/templates/Foundation/Experience Accelerator/Grid/Grid Definition Items/Device children/Checkbox/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161216T081457Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7608add1-7ed5-4ea5-b611-12dbed2ae38d"
