---
ID: "64295b86-db64-4a64-8f06-6280b3d94c52"
Parent: "c5ea4fed-f0fa-4e0f-a3ef-793577b375da"
Template: "c5ea4fed-f0fa-4e0f-a3ef-793577b375da"
Path: /sitecore/templates/Feature/Experience Accelerator/Search/Rendering Parameters/Dropdown Filter/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140731T135557
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4d14accf-5706-4ec3-a61e-6c8cd6c91b7a"
    - ID: "91ed9872-2007-47e9-bf01-1292c1b261b2"
      Hint: SortOrder
      Value: SortByNames
