---
ID: "1225409a-1a4b-4393-88dd-1ee0918f3dfd"
Parent: "b682562e-0af6-4b3e-9e3b-45273bbe152d"
Template: "b682562e-0af6-4b3e-9e3b-45273bbe152d"
Path: /sitecore/templates/Feature/Experience Accelerator/Search/Datasource/Page Size/PageSize/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140725T153342
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ed42f7f-ffa0-4463-975e-ea320cd42217"
