---
ID: "a6c854ea-ab8a-43f2-a226-53bb0a854db2"
Parent: "6bf19f1c-da51-477f-b7d9-b49b41fd1578"
Template: "6bf19f1c-da51-477f-b7d9-b49b41fd1578"
Path: /sitecore/templates/Feature/Experience Accelerator/Overlays/Overlay Content/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{0349837C-0A21-4138-B4F8-A5A67756AA16}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160601T101206Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "07c43ac6-6754-4c50-9e6d-b5f7315ac8a3"
